version: '3.1'

services:
  postgresql-book-shell:
    image: bitnami/postgresql:14.17.0
    ports:
      - "5433:5432"
    volumes:
      - ~/docker/postgresql-book-shell:/bitnami/postgresql-book-shell
    environment:
      - POSTGRESQL_PASSWORD=admin
      - POSTGRESQL_USERNAME=admin
      - POSTGRESQL_DATABASE=library